### ISSUE TITLE
Error while compiling the project in gulp

### ISSUE THREAD

**Issue by strukove** [euvl/vue-js-modal#7]
Hi,
I'm getting this error during compiling the project using gulp browserify

> Cannot find module '!!./../node_modules/css-loader/index.js!./../node_modules/vue-loader/lib/style-rewriter.js?id=data-v-60fe12fc!./../node_modules/sass-loader/lib/loader.js!./../node_modules/vue-loader/lib/selector.js?type=styles&index=0!./Resizer.vue' from 'c:\GIT\Rockwool\Website\static\node_modules\vue-js-modal\dist

**Comment by euvl** [comment]
Hey @strukove. I was using `sass` in the project, you might want to add `sass-loader` and `node-sass` to your deps.

Could you please give me a code example of how you do it or create a sample project so i could take a look?

**Comment by euvl** [comment]
Hey again @strukove , i've just pushed release 1.0.19 that does not use sass at all. 

There was not that much css to use preprocessor tbh, hope it will fix your problem.

**Comment by TheLonelinessOfHS** [comment]
Hello. I've got exactly the same problem.

**Comment by TheLonelinessOfHS** [comment]
WIth version 1.0.19

**Comment by strukove** [comment]
Great, thanks)

**Comment by strukove** [comment]
I've just tried to use it again (installed it from npm from scratch) and I still have this issue:
 

> Cannot find module '!!./../node_modules/css-loader/index.js?minimize!./../node_modules/vue-loader/lib/style-rewriter.js?id=data-v-40dd3b1e&scoped=true!./../node_modules/vue-loader/lib/selector.js?type=styles&index=0!./Modal.vue' from 'c:\GIT\Rockwool\Website\static\node_modules\vue-js-modal\dist'

**Comment by euvl** [comment]
Will try to spend more time on this issue in upcoming week

**Comment by euvl** [comment]
It is clearly some mess in vue dependencies & gulp & windows, i am afraid i didn't manage to replicate the problem. 
Hopefully you have found a solution, lemme know if this is still an issue
